# Generated by Django 3.0.5 on 2020-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('units', models.CharField(choices=[('oz', 'ounce'), ('floz', 'fluid ounce'), ('pc', 'piece'), ('slc', 'slice')], max_length=4)),
            ],
        ),
    ]
