# Generated by Django 3.0.5 on 2020-04-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_remove_pizza_toppings'),
        ('toppings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', to='pizzas.Pizza'),
        ),
    ]
