# Generated by Django 3.0.5 on 2020-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_remove_pizza_toppings'),
        ('toppings', '0002_topping_pizzas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='pizzas',
            field=models.ManyToManyField(to='pizzas.Pizza'),
        ),
    ]
